<?php

/**
 * @var Zend_View $this
 * @var Application_Model_Currency $entry
 */

?>
<!-- application/views/scripts/currency/index.phtml -->
<!---->
<!--<p><a href="--><?php //echo $this->url(
//		array(
//			'controller' => 'guestbook',
//			'action'     => 'sign'
//		),
//		'default',
//		true) ?><!--">Sign Our Guestbook</a></p>-->

Currency Entries: <br />
<dl>
	<?php foreach ($this->entries as $entry): ?>
		<dt><?php echo $this->escape($entry->abbr) ?></dt>
		<dd>
			<?php echo $this->escape($entry->name) ?>
            <?php if ($entry->isActive): ?>
                (active)
            <?php else: ?>
                (not active)
            <?php endif ?>
		</dd>
	<?php endforeach ?>
</dl>